use_frameworks!

target 'SHViewPager_Example' do
  pod 'SHViewPager', :path => '../'
  target 'SHViewPager_Tests' do
    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
